from pathlib import Path
code = [
    '"""Sampling methods for diffusion models (Euler-Maruyama, DPM-Solver++)."""',
    '',
    'import torch',
    'import numpy as np',
    'from tqdm import tqdm',
    '',
    '',
    'class EulerMaruyamaSampler:',
    '    """Basic Euler-Maruyama sampler for reverse-time SDE."""',
    '',
    '    def __init__(self, config, sde, score_net):',
    '        self.config = config',
    '        self.sde = sde',
    '        self.score_net = score_net',
    '        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")',
    '        self.score_net.to(self.device).eval()',
    '',
    '    def sample(self, num_samples: int, latent_dim: int, num_steps: int = 1000) -> np.ndarray:',
    '        """Generate samples from trained diffusion model."""',
    '        with torch.no_grad():',
    '            # Start from noise ~ N(0, I)',
    '            x = torch.randn(num_samples, latent_dim, device=self.device)',
    '',
    '            # Reverse-time SDE discretization',
    '            dt = self.sde.T / num_steps',
    '            timesteps = torch.linspace(self.sde.T, 0, num_steps + 1, device=self.device)',
    '',
    '            for i in tqdm(range(num_steps), desc="Sampling"):',
    '                t = timesteps[i].expand(num_samples)',
    '',
    '                # Reverse drift and diffusion',
    '                drift = self.sde.drift(x, t)',
    '                score = self.score_net(x, t)',
    '                diffusion = self.sde.diffusion(x, t)',
    '',
    '                # Euler-Maruyama step',
    '                z = torch.randn_like(x) if i < num_steps - 1 else 0',
    '                x = x - (drift - diffusion**2 * score) * dt + diffusion * np.sqrt(dt) * z',
    '',
    '        return x.cpu().numpy()',
    '',
    '',
    'class DPMSolverPlusPlus:',
    '    """DPM-Solver++ (2nd order) for faster sampling."""',
    '',
    '    def __init__(self, config, sde, score_net):',
    '        self.config = config',
    '        self.sde = sde',
    '        self.score_net = score_net',
    '        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")',
    '        self.score_net.to(self.device).eval()',
    '',
    '    def sample(self, num_samples: int, latent_dim: int, num_steps: int = 20) -> np.ndarray:',
    '        """Generate samples using DPM-Solver++ (much fewer steps needed)."""',
    '        with torch.no_grad():',
    '            x = torch.randn(num_samples, latent_dim, device=self.device)',
    '            timesteps = torch.linspace(self.sde.T, 1e-3, num_steps + 1, device=self.device)',
    '',
    '            for i in tqdm(range(num_steps), desc="DPM-Solver++"):',
    '                t_curr = timesteps[i].expand(num_samples)',
    '                t_next = timesteps[i + 1].expand(num_samples)',
    '',
    '                # Predict score',
    '                score = self.score_net(x, t_curr)',
    '',
    '                # Convert score to epsilon prediction',
    '                mean, std = self.sde.marginal_params(x, t_curr)',
    '                eps_pred = -score * std',
    '',
    '                # DPM-Solver++ update (simplified 1st order)',
    '                # For full 2nd order, need to store previous prediction',
    '                log_alpha_curr = -0.25 * t_curr**2 * (self.sde.beta_max - self.sde.beta_min) - 0.5 * t_curr * self.sde.beta_min',
    '                log_alpha_next = -0.25 * t_next**2 * (self.sde.beta_max - self.sde.beta_min) - 0.5 * t_next * self.sde.beta_min',
    '',
    '                alpha_curr = torch.exp(log_alpha_curr.unsqueeze(-1))',
    '                alpha_next = torch.exp(log_alpha_next.unsqueeze(-1))',
    '                sigma_curr = torch.sqrt(1 - alpha_curr**2)',
    '                sigma_next = torch.sqrt(1 - alpha_next**2)',
    '',
    '                x = (alpha_next / alpha_curr) * x + sigma_next * (1 - alpha_curr / alpha_next) * eps_pred',
    '',
    '        return x.cpu().numpy()',
]
Path('diffusion_factor_model/sampling/sampler.py').write_text('\n'.join(code), encoding='utf-8')
print("sampling/sampler.py OK")
