from pathlib import Path
code = [
    '"""Residual modeling with GJR-GARCH for idiosyncratic returns."""',
    '',
    'import numpy as np',
    'import pandas as pd',
    'from arch import arch_model',
    'from typing import Dict',
    'from tqdm import tqdm',
    '',
    '',
    'class GARCHModeler:',
    '    """Model idiosyncratic residuals with GJR-GARCH(1,1) + Student-t."""',
    '',
    '    def __init__(self, config):',
    '        self.config = config',
    '        self.models = {}',
    '',
    '    def fit_all(self, residuals: pd.DataFrame) -> Dict:',
    '        """Fit GJR-GARCH to each stock\'s residual series."""',
    '        results = {}',
    '        for col in tqdm(residuals.columns, desc="Fitting GARCH"):',
    '            series = residuals[col].dropna() * 100  # scale to pct',
    '            if len(series) < 100:',
    '                continue',
    '            try:',
    '                model = arch_model(',
    '                    series,',
    '                    vol="Garch",',
    '                    p=1, q=1, o=1,',
    '                    dist="studentst",',
    '                    rescale=False',
    '                )',
    '                res = model.fit(disp="off")',
    '                results[col] = res',
    '            except Exception:',
    '                continue',
    '',
    '        print(f"Fitted GARCH on {len(results)}/{len(residuals.columns)} stocks")',
    '        self.models = results',
    '        return results',
    '',
    '    def sample(self, stock: str, horizon: int) -> np.ndarray:',
    '        """Sample future residuals from fitted model."""',
    '        if stock not in self.models:',
    '            raise KeyError(f"No model for {stock}")',
    '        res = self.models[stock]',
    '        sim = res.forecast(horizon=horizon, method="simulation", simulations=1)',
    '        return sim.simulations.values[0, :, 0] / 100',
    '',
    '    def sample_all(self, horizon: int) -> pd.DataFrame:',
    '        """Sample residuals for all stocks."""',
    '        data = {}',
    '        for stock in self.models:',
    '            data[stock] = self.sample(stock, horizon)',
    '        return pd.DataFrame(data)',
]
Path('diffusion_factor_model/residuals/garch.py').write_text('\n'.join(code), encoding='utf-8')
print("residuals/garch.py OK")
