from pathlib import Path
code = [
    '"""Latent space parametrization combining mean and volatility factors."""',
    '',
    'import numpy as np',
    'import pandas as pd',
    'from typing import Dict, Tuple',
    '',
    '',
    'class LatentParametrizer:',
    '    """Parametrize latent space from mean and volatility factors."""',
    '',
    '    def __init__(self, config):',
    '        self.config = config',
    '        self.use_log_variance = config.latent.use_log_variance',
    '',
    '    def parametrize(self, mean_factors: Dict, vol_factors: Dict) -> Tuple[np.ndarray, Dict]:',
    '        """Combine mean and volatility factors into latent representation.',
    '',
    '        Returns:',
    '            latent: (T, D) latent matrix where D = n_mean + n_vol',
    '            metadata: dict with factor counts and indices',
    '        """',
    '        mean_df = mean_factors["factors"]',
    '        vol_df = vol_factors["factors"]',
    '',
    '        # Align on common dates',
    '        common_idx = mean_df.index.intersection(vol_df.index)',
    '        mean_df = mean_df.loc[common_idx]',
    '        vol_df = vol_df.loc[common_idx]',
    '',
    '        # Combine: [mean_factors | log_variance_factors]',
    '        if self.use_log_variance:',
    '            vol_transformed = np.log(np.abs(vol_df) + 1e-8)',
    '        else:',
    '            vol_transformed = vol_df',
    '',
    '        latent = np.hstack([mean_df.values, vol_transformed.values])',
    '',
    '        metadata = {',
    '            "n_mean_factors": mean_df.shape[1],',
    '            "n_vol_factors": vol_df.shape[1],',
    '            "mean_names": list(mean_df.columns),',
    '            "vol_names": list(vol_df.columns),',
    '            "dates": common_idx',
    '        }',
    '',
    '        print(f"Latent space: {latent.shape} (mean: {mean_df.shape[1]}, vol: {vol_df.shape[1]})")',
    '',
    '        return latent, metadata',
    '',
    '    def deparametrize(self, latent: np.ndarray, metadata: Dict) -> Tuple[pd.DataFrame, pd.DataFrame]:',
    '        """Split latent back into mean and volatility factors."""',
    '        n_mean = metadata["n_mean_factors"]',
    '        n_vol = metadata["n_vol_factors"]',
    '',
    '        mean_values = latent[:, :n_mean]',
    '        vol_values = latent[:, n_mean:n_mean+n_vol]',
    '',
    '        if self.use_log_variance:',
    '            vol_values = np.exp(vol_values) - 1e-8',
    '',
    '        mean_df = pd.DataFrame(mean_values, index=metadata["dates"], columns=metadata["mean_names"])',
    '        vol_df = pd.DataFrame(vol_values, index=metadata["dates"], columns=metadata["vol_names"])',
    '',
    '        return mean_df, vol_df',
]
Path('diffusion_factor_model/latent/parametrizer.py').write_text('\n'.join(code), encoding='utf-8')
print("latent/parametrizer.py OK")
