from pathlib import Path
code = [
    '"""Reconstruct stock returns from latent factors."""',
    '',
    'import numpy as np',
    'import pandas as pd',
    'from typing import Dict',
    '',
    '',
    'class ReturnReconstructor:',
    '    """Convert latent factor samples back to stock returns."""',
    '',
    '    def __init__(self, config, mean_factor_results, vol_factor_results):',
    '        self.config = config',
    '        self.mean_loadings = mean_factor_results["loadings"]',
    '        self.vol_loadings = vol_factor_results["loadings"]',
    '',
    '    def reconstruct(self, latent_samples: np.ndarray, residual_samples: pd.DataFrame) -> pd.DataFrame:',
    '        """Reconstruct stock returns from latent factors.',
    '',
    '        Args:',
    '            latent_samples: (num_samples, latent_dim) from diffusion model',
    '            residual_samples: (num_samples, num_stocks) from GARCH',
    '',
    '        Returns:',
    '            returns_df: (num_samples, num_stocks) reconstructed returns',
    '        """',
    '        num_samples = latent_samples.shape[0]',
    '',
    '        # Split latent into mean and vol components',
    '        n_mean = len(self.mean_loadings.columns)',
    '        mean_factors = latent_samples[:, :n_mean]',
    '        vol_factors = latent_samples[:, n_mean:]',
    '',
    '        # Reconstruct mean returns: R_mean = F_mean @ beta_mean.T',
    '        mean_returns = mean_factors @ self.mean_loadings.values.T',
    '',
    '        # Reconstruct vol component (currently simplified)',
    '        # In full implementation, would reconstruct time-varying covariance',
    '        vol_component = np.zeros_like(mean_returns)',
    '',
    '        # Add residuals',
    '        if residual_samples is not None:',
    '            residual_array = residual_samples.values[:, :mean_returns.shape[1]]',
    '            returns = mean_returns + vol_component + residual_array',
    '        else:',
    '            returns = mean_returns + vol_component',
    '',
    '        # Create DataFrame with stock names',
    '        stock_names = list(self.mean_loadings.index)',
    '        returns_df = pd.DataFrame(returns, columns=stock_names)',
    '',
    '        print(f"Reconstructed returns: {returns_df.shape}")',
    '        return returns_df',
]
Path('diffusion_factor_model/reconstruction/reconstructor.py').write_text('\n'.join(code), encoding='utf-8')
print("reconstruction/reconstructor.py OK")
