from pathlib import Path
code = [
    '"""Data loader for stock returns using AKShare."""',
    '',
    'import akshare as ak',
    'import pandas as pd',
    'import numpy as np',
    'from typing import List, Tuple, Optional',
    'from pathlib import Path',
    'from tqdm import tqdm',
    '',
    '',
    'class StockDataLoader:',
    '    """Load and preprocess stock data from AKShare."""',
    '',
    '    def __init__(self, config):',
    '        self.config = config',
    '        self.universe = config.data.universe',
    '        self.start_date = config.data.start_date',
    '        self.end_date = config.data.end_date',
    '        self.cache_dir = Path(config.data_dir) / "cache"',
    '        self.cache_dir.mkdir(parents=True, exist_ok=True)',
    '',
    '    def get_stock_list(self) -> List[str]:',
    '        """Get list of stocks in the universe."""',
    '        if self.universe == "hs300":',
    '            df = ak.index_stock_cons(symbol="000300")',
    "            return df['品种代码'].tolist()",
    '        elif self.universe == "hs500":',
    '            df = ak.index_stock_cons(symbol="000905")',
    "            return df['品种代码'].tolist()",
    '        elif self.universe == "all":',
    '            df = ak.stock_zh_a_spot_em()',
    "            return df['代码'].tolist()",
    '        else:',
    '            raise ValueError(f"Unknown universe: {self.universe}")',
    '',
    '    def load_single_stock(self, stock_code: str) -> Optional[pd.DataFrame]:',
    '        """Load daily OHLCV data for a single stock."""',
    '        cache_file = self.cache_dir / f"{stock_code}.parquet"',
    '        if cache_file.exists():',
    '            return pd.read_parquet(cache_file)',
    '        try:',
    '            df = ak.stock_zh_a_hist(',
    '                symbol=stock_code, period="daily",',
    '                start_date=self.start_date, end_date=self.end_date, adjust="hfq"',
    '            )',
    "            df['日期'] = pd.to_datetime(df['日期'])",
    "            df = df.set_index('日期')",
    '            df = df.rename(columns={',
    "                '开盘': 'open', '收盘': 'close',",
    "                '最高': 'high', '最低': 'low',",
    "                '成交量': 'volume', '成交额': 'amount',",
    "                '换手率': 'turnover'",
    '            })',
    '            df.to_parquet(cache_file)',
    '            return df',
    '        except Exception as e:',
    '            print(f"Failed to load {stock_code}: {e}")',
    '            return None',
    '',
    '    def load_returns_matrix(self, max_stocks: Optional[int] = None) -> Tuple[pd.DataFrame, List[str]]:',
    '        """Load returns matrix for all stocks in universe."""',
    '        stock_list = self.get_stock_list()',
    '        if max_stocks:',
    '            stock_list = stock_list[:max_stocks]',
    '        print(f"Loading data for {len(stock_list)} stocks...")',
    '        returns_dict = {}',
    '        for i, code in enumerate(tqdm(stock_list, desc="Loading stocks")):',
    '            df = self.load_single_stock(code)',
    '            if df is not None and "close" in df.columns:',
    '                returns = df["close"].pct_change().dropna()',
    '                returns_dict[code] = returns',
    '        returns_df = pd.DataFrame(returns_dict).dropna(how="all").fillna(0)',
    '        print(f"Loaded {len(returns_df.columns)} stocks, {len(returns_df)} trading days")',
    '        return returns_df, list(returns_df.columns)',
    '',
    '    def load_market_index(self, index_code: str = "000300") -> Optional[pd.Series]:',
    '        """Load market index returns (default: CSI 300)."""',
    '        cache_file = self.cache_dir / f"index_{index_code}.parquet"',
    '        if cache_file.exists():',
    '            df = pd.read_parquet(cache_file)',
    '            return df["close"].pct_change().dropna()',
    '        try:',
    '            df = ak.stock_zh_index_daily(symbol=f"sh{index_code}")',
    "            df['date'] = pd.to_datetime(df['date'])",
    "            df = df.set_index('date')",
    '            df = df[(df.index >= self.start_date) & (df.index <= self.end_date)]',
    '            df.to_parquet(cache_file)',
    '            return df["close"].pct_change().dropna()',
    '        except Exception as e:',
    '            print(f"Failed to load index {index_code}: {e}")',
    '            return None',
    '',
    '',
    'class SyntheticDataLoader:',
    '    """Generate synthetic stock returns for testing."""',
    '',
    '    def generate(self, n_stocks=100, n_days=2520, n_factors=5) -> pd.DataFrame:',
    '        """Generate synthetic returns using factor model."""',
    '        np.random.seed(42)',
    '        factor_returns = np.random.randn(n_days, n_factors) * 0.02',
    '        betas = np.random.randn(n_stocks, n_factors) * 0.5',
    '        idio_returns = np.random.randn(n_days, n_stocks) * 0.03',
    '        returns = factor_returns @ betas.T + idio_returns',
    '        dates = pd.date_range(start="2015-01-01", periods=n_days, freq="B")',
    '        names = [f"STOCK_{i:03d}" for i in range(n_stocks)]',
    '        return pd.DataFrame(returns, index=dates, columns=names)',
]
Path('diffusion_factor_model/data/loader.py').write_text('\n'.join(code), encoding='utf-8')
print("data/loader.py OK")
