from pathlib import Path
code = [
    '"""Score network architectures for diffusion models."""',
    '',
    'import torch',
    'import torch.nn as nn',
    'import math',
    '',
    '',
    'class SinusoidalPositionalEmbedding(nn.Module):',
    '    """Sinusoidal time embedding."""',
    '',
    '    def __init__(self, embedding_dim):',
    '        super().__init__()',
    '        self.embedding_dim = embedding_dim',
    '',
    '    def forward(self, t: torch.Tensor) -> torch.Tensor:',
    '        half_dim = self.embedding_dim // 2',
    '        emb = math.log(10000) / (half_dim - 1)',
    '        emb = torch.exp(torch.arange(half_dim, device=t.device) * -emb)',
    '        emb = t.unsqueeze(-1) * emb.unsqueeze(0)',
    '        emb = torch.cat([torch.sin(emb), torch.cos(emb)], dim=-1)',
    '        return emb',
    '',
    '',
    'class ResidualMLP(nn.Module):',
    '    """Residual MLP with FiLM conditioning."""',
    '',
    '    def __init__(self, input_dim, hidden_dim, num_layers, dropout=0.1):',
    '        super().__init__()',
    '        self.input_proj = nn.Linear(input_dim, hidden_dim)',
    '        self.time_embed = SinusoidalPositionalEmbedding(hidden_dim)',
    '        self.time_proj = nn.Linear(hidden_dim, hidden_dim)',
    '',
    '        self.blocks = nn.ModuleList()',
    '        for _ in range(num_layers):',
    '            self.blocks.append(nn.ModuleDict({',
    '                "norm": nn.LayerNorm(hidden_dim),',
    '                "fc1": nn.Linear(hidden_dim, hidden_dim),',
    '                "fc2": nn.Linear(hidden_dim, hidden_dim),',
    '                "dropout": nn.Dropout(dropout)',
    '            }))',
    '',
    '        self.output_proj = nn.Linear(hidden_dim, input_dim)',
    '',
    '    def forward(self, x: torch.Tensor, t: torch.Tensor) -> torch.Tensor:',
    '        """',
    '        Args:',
    '            x: (batch, input_dim) latent state',
    '            t: (batch,) time in [0, 1]',
    '        """',
    '        h = self.input_proj(x)',
    '        t_emb = self.time_embed(t)',
    '        t_emb = self.time_proj(t_emb)',
    '',
    '        for block in self.blocks:',
    '            residual = h',
    '            h = block["norm"](h)',
    '            h = h + t_emb  # FiLM conditioning',
    '            h = torch.nn.functional.silu(h)',
    '            h = block["fc1"](h)',
    '            h = torch.nn.functional.silu(h)',
    '            h = block["fc2"](h)',
    '            h = block["dropout"](h)',
    '            h = h + residual',
    '',
    '        return self.output_proj(h)',
    '',
    '',
    'class ScoreNetwork(nn.Module):',
    '    """Score network s_theta(x, t) for diffusion model."""',
    '',
    '    def __init__(self, input_dim, hidden_dim=256, num_layers=6, dropout=0.1):',
    '        super().__init__()',
    '        self.mlp = ResidualMLP(input_dim, hidden_dim, num_layers, dropout)',
    '',
    '    def forward(self, x: torch.Tensor, t: torch.Tensor) -> torch.Tensor:',
    '        """Compute score function estimate."""',
    '        return self.mlp(x, t)',
]
Path('diffusion_factor_model/diffusion/score_net.py').write_text('\n'.join(code), encoding='utf-8')
print("diffusion/score_net.py OK")
