from pathlib import Path
code = [
    '"""Factor extraction: mean factors (FF-style) and volatility factors (PCA)."""',
    '',
    'import numpy as np',
    'import pandas as pd',
    'from sklearn.decomposition import PCA',
    'from typing import Dict, Tuple',
    '',
    '',
    'class FactorExtractor:',
    '    """Extract mean and volatility factors from returns."""',
    '',
    '    def __init__(self, config):',
    '        self.config = config',
    '        self.n_vol_factors = config.factors.n_vol_factors',
    '',
    '    def extract_mean_factors(self, returns: pd.DataFrame, market_returns: pd.Series) -> Dict[str, pd.DataFrame]:',
    '        """Extract mean factors: market, size, value, momentum, etc."""',
    '        factors = {}',
    '        loadings = {}',
    '',
    '        # Market factor',
    '        factors["market"] = market_returns.reindex(returns.index).fillna(0)',
    '',
    '        # Size factor (SMB) - need market cap data, placeholder for now',
    '        # factors["size"] = self._compute_size_factor(returns)',
    '',
    '        # Value factor (HML) - need book-to-market data, placeholder for now',
    '        # factors["value"] = self._compute_value_factor(returns)',
    '',
    '        # Momentum factor (UMD)',
    '        factors["momentum"] = self._compute_momentum_factor(returns)',
    '',
    '        # Short-term reversal',
    '        factors["reversal"] = self._compute_reversal_factor(returns)',
    '',
    '        factors_df = pd.DataFrame(factors)',
    '',
    '        # Compute factor loadings via time-series regression',
    '        import statsmodels.api as sm',
    '        loadings_dict = {}',
    '        for col in returns.columns:',
    '            y = returns[col].dropna()',
    '            X = sm.add_constant(factors_df.loc[y.index].dropna())',
    '            common_idx = y.index.intersection(X.index)',
    '            if len(common_idx) < 50:',
    '                continue',
    '            y_common = y.loc[common_idx]',
    '            X_common = X.loc[common_idx]',
    '            model = sm.OLS(y_common, X_common).fit()',
    '            loadings_dict[col] = model.params.drop("const")',
    '',
    '        loadings_df = pd.DataFrame(loadings_dict).T',
    '',
    '        return {',
    '            "factors": factors_df,',
    '            "loadings": loadings_df',
    '        }',
    '',
    '    def extract_volatility_factors(self, residuals: pd.DataFrame) -> Dict[str, pd.DataFrame]:',
    '        """Extract volatility factors via PCA on residuals."""',
    '        pca = PCA(n_components=min(self.n_vol_factors, residuals.shape[1] - 1))',
    '        vol_factors = pca.fit_transform(residuals)',
    '        explained_var = pca.explained_variance_ratio_.cumsum()',
    '        print(f"PCA explained variance: {explained_var[-1]:.2%} with {len(explained_var)} factors")',
    '',
    '        return {',
    '            "factors": pd.DataFrame(vol_factors, index=residuals.index),',
    '            "loadings": pd.DataFrame(pca.components_.T, index=residuals.columns),',
    '            "explained_variance": explained_var',
    '        }',
    '',
    '    def compute_residuals(self, returns: pd.DataFrame, mean_factors: Dict) -> pd.DataFrame:',
    '        """Compute residuals after removing mean factor effects."""',
    '        factors_df = mean_factors["factors"]',
    '        loadings_df = mean_factors["loadings"]',
    '',
    '        residuals = returns.copy()',
    '        for col in returns.columns:',
    '            if col in loadings_df.index:',
    '                beta = loadings_df.loc[col]',
    '                residuals[col] = returns[col] - (factors_df.loc[returns.index] @ beta)',
    '',
    '        return residuals',
    '',
    '    def _compute_momentum_factor(self, returns: pd.DataFrame, lookback: int = 252) -> pd.Series:',
    '        """Compute momentum factor (12-1 month)."""',
    '        # 12-month momentum excluding last month',
    '        mom_long = returns.rolling(lookback).mean()',
    '        mom_short = returns.rolling(21).mean()',
    '        momentum = (mom_long - mom_short).mean(axis=1)',
    '        return momentum',
    '',
    '    def _compute_reversal_factor(self, returns: pd.DataFrame, lookback: int = 21) -> pd.Series:',
    '        """Compute short-term reversal factor."""',
    '        reversal = returns.rolling(lookback).mean().mean(axis=1) * -1',
    '        return reversal',
]
Path('diffusion_factor_model/factors/extractor.py').write_text('\n'.join(code), encoding='utf-8')
print("factors/extractor.py OK")
